spring:
  application:
    name: music-poll
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:file:~/test
    username: sa
    password: 
    driverClassName: org.h2.Driver
        
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    defer-datasource-initialization: true    
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true 