spring:
  application:
    name: music-poll
  cache:
    type: none
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/encuesta
    username: postgres
    password: 123asd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    database: postgresql
    # Logger configuration
logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug
# Server configuration
server:
  port: 8080 #set your port        